# Generated by Django 3.2.9 on 2021-12-02 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211202_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='recieved_oon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
