# Generated by Django 3.2.9 on 2021-12-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211202_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='recieved_oon',
            new_name='recieved_on',
        ),
    ]
