# Generated by Django 3.2.9 on 2022-06-03 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_auto_20220530_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsapplied',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default=1, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='jobsapplied',
            unique_together={('job', 'user')},
        ),
    ]
